defaults:
  - _self_

# Scene Output Settings
dataset_name: hm3d
output_path: /home/miguel/Documents/Datasets
scene_name: 00829-QaLdnwvtxbs

# Habitat Setting
# temp
default_agent: 0

# Scene Configuration
# load from scene config
# if load from scene config, then we no need define scene path in the following
load_from_config: false
scene_config: /home/eku/workspace/dataset/HM3D_collect/00829-QaLdnwvtxbs/dynamic_scene_config/0117.json

# HM3D
scene_path: /home/miguel/Documents/Datasets/hm3d/val/00829-QaLdnwvtxbs/QaLdnwvtxbs.basis.glb
scene_dataset_config: /home/miguel/Documents/Datasets/hm3d/val/hm3d_annotated_basis.scene_dataset_config.json

# MP3D
# scene_path: /home/eku/workspace/habitat-sim/data/mp3d_example/17DRP5sb8fy/17DRP5sb8fy.glb
# scene_dataset_config: /home/eku/workspace/habitat-sim/data/mp3d_example/mp3d.scene_dataset_config.json

# Replica
# scene_path: /home/eku/workspace/dataset/Replica-Dataset/Replica_original/room_0/habitat/mesh_semantic.ply
# scene_dataset_config: /home/eku/workspace/dataset/Replica-Dataset/Replica_original/replica.scene_dataset_config.json


# Object Path
objects_path: /home/miguel/Documents/Datasets/ycb/reduced_configs

# Sensor and Camera Settings
data_cfg:
  seed: 12
  rgb: true
  depth: true
  semantic: true
  resolution:
    w: 1200
    h: 680
  camera_height: 1.5

# Agent Movement
movement_cfg:
  move_forward: 0.4
  move_backward: 0.4
  turn_left: 3
  turn_right: 3
  look_up: 3
  look_down: 3

physics_cfg:
  enable_physics: true

# Placable Categories
placable_categories:
  - table
  - counter
  - desk
  - shelving
  - cabinet
  - bed
  - sofa
  - stool

# Show the bounding box of all the placable categories
show_placable_categories: False

frame_rate: 30.0

# Publish ROS2 topics
use_ros: False
# The recording can also record the rosbag along with the rgbd raw data
record_rosbag: False

# PLACEHOLDER, for mapping semantic_id to object handle
# Do not Delete this holder
id_handle_dict: {}
